# Generated by Django 5.0.6 on 2024-06-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryservice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical category service', 'verbose_name_plural': 'historical category services'},
        ),
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical indicator', 'verbose_name_plural': 'historical indicators'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={},
        ),
        migrations.AlterModelTable(
            name='categoryservice',
            table='CategoriaServicio',
        ),
        migrations.AlterModelTable(
            name='indicator',
            table='Indicator',
        ),
        migrations.AlterModelTable(
            name='service',
            table='Servicios',
        ),
    ]
